import streamlit as st


EXPLANATIONS = {

    "Current Price":
        "The latest asset price supplied by the backend.",

    "Total Return":
        "The overall percentage change during the selected period.",

    "Volatility":
        "Shows how much the asset's returns have historically fluctuated.",

    "Sharpe Ratio":
        "Measures return relative to the amount of volatility or risk taken.",

    "Maximum Drawdown":
        "The largest historical decline from a previous peak.",

    "SMA":
        "Simple Moving Average. It represents the average price over a selected period.",

    "EMA":
        "Exponential Moving Average. It gives greater importance to recent prices.",

    "Momentum":
        "A backend-provided measure describing the direction or strength of recent price movement.",

    "Strategy Return":
        "The return generated by the selected backtesting strategy.",

    "Buy & Hold Return":
        "The return from holding the selected asset throughout the backtest period."
}


def get_explanation(
    metric
):

    return EXPLANATIONS.get(
        metric,
        "This metric is provided by the quantitative backend."
    )


def info_box(
    title,
    text=None
):

    if text is None:

        text = get_explanation(
            title
        )

    with st.expander(
        f"ℹ️ {title}"
    ):

        st.write(text)


def status_badge(
    status
):

    if status is None:

        return

    status_text = str(
        status
    ).strip()

    normalized = status_text.lower()

    if normalized in {
        "good",
        "positive",
        "strong",
        "bullish"
    }:

        css_class = "status-good"

    elif normalized in {
        "weak",
        "negative",
        "bearish"
    }:

        css_class = "status-weak"

    else:

        css_class = "status-neutral"

    st.markdown(
        f"""
        <span class="status-badge {css_class}">
            {status_text.upper()}
        </span>
        """,
        unsafe_allow_html=True
    )
