import streamlit as st

from frontend.components.cards import (
    hero_header
)

from frontend.components.chat import (
    render_chat_history,
    chat_input
)


def render(
    ask_ai
):

    hero_header(
        "FinSight AI Assistant",
        "Ask natural-language questions about the analyzed financial data."
    )

    st.caption(
        "AI responses are generated by the project's AI backend."
    )

    if "finsight_chat" not in st.session_state:

        st.session_state[
            "finsight_chat"
        ] = []

    render_chat_history(
        st.session_state[
            "finsight_chat"
        ]
    )

    question = chat_input()

    if question:

        st.session_state[
            "finsight_chat"
        ].append(
            {
                "role":
                    "user",

                "content":
                    question
            }
        )

        with st.spinner(
            "FinSight AI is analyzing..."
        ):

            try:

                answer = ask_ai(
                    question
                )

            except Exception:

                answer = (
                    "The AI service is currently "
                    "unavailable. Please try again."
                )

        st.session_state[
            "finsight_chat"
        ].append(
            {
                "role":
                    "assistant",

                "content":
                    answer
            }
        )

        st.rerun()

    if st.session_state[
        "finsight_chat"
    ]:

        if st.button(
            "Clear Conversation"
        ):

            st.session_state[
                "finsight_chat"
            ] = []

            st.rerun()
